/**
 * Everything the process reads from its environment, read once.
 *
 * Missing values fail here, at boot, naming the variable — rather than at the
 * first request that happens to need one.
 */
export interface AppConfig {
  port: number;
  /** Where the SQLite file lives. `:memory:` is legal and is what tests use. */
  databasePath: string;
  /**
   * The site's own origin, scheme included.
   *
   * Load-bearing twice over: it is the only `Origin` the mutation guard will
   * accept, and it is what decides whether cookies are marked `Secure`.
   */
  siteOrigin: string;
  /**
   * The Freesound API key, or null where the deployment has none.
   *
   * Optional on purpose, including in production: sound search is a convenience
   * in a desktop app, and a missing key should cost that one feature rather
   * than stop the site from booting. `FreesoundService` answers "not
   * configured" and the tracker's picker hides its search box.
   */
  freesoundToken: string | null;
  /**
   * The Steam Web API key, or null where the deployment has none.
   *
   * Optional even in production, and deliberately: it is only used to fetch a
   * display name and avatar *after* OpenID has already established who somebody
   * is. Without it, sign-in still works and people get a persona derived from
   * their SteamID. Making it required would mean a missing key stops the site
   * from booting over a decoration.
   */
  steamApiKey: string | null;
  /**
   * Discord's OAuth2 application, or null where the deployment has none.
   *
   * Both halves or neither: an id without a secret is a sign-in button that
   * always fails, which is worse than a button that is not offered. The
   * sign-in screen asks `GET /auth/providers` which doors exist, so a deploy
   * without these keys simply does not show Discord — the same way a missing
   * Steam key degrades rather than breaks.
   */
  discord: { clientId: string; clientSecret: string } | null;
  /**
   * Where the extracted icons live, for the social-card renderer.
   *
   * The shared package's `public/` directory: the same tree Caddy serves to
   * browsers, copied into the API image because a card is composed server-side
   * from hero portraits and item icons and there is nowhere else to read them
   * from. See infra/api.Dockerfile.
   *
   * A wrong or missing path is not fatal. `CardService` draws the card without
   * the pictures it cannot find, because a link preview with no portrait on it
   * is a much better outcome than a 500 on somebody's shared link.
   */
  assetsDir: string;
  /**
   * Where the site's own artwork lives — the wordmark, and nothing else so far.
   *
   * Separate from `assetsDir` because the two are different kinds of thing and
   * come from different places. `assetsDir` is the extraction pipeline's output,
   * shared with the browser and regenerated by a parser run; this is the site's
   * branding, which lives with the webapp that draws it everywhere else.
   *
   * Missing is survivable in the same way: a card with no wordmark on it falls
   * back to the site's name as text.
   */
  brandDir: string;
  /**
   * Where rendered cards are kept.
   *
   * Beside the database on the data volume rather than in the image, because a
   * card outlives a deploy and rasterizing one costs far more than reading it
   * back. Keyed by slug and `updated_at`, so an edited build gets a new file and
   * the old one is removed — see `CardService`.
   */
  cardCacheDir: string;
  isProduction: boolean;
}

function required(name: string): string {
  const value = process.env[name];
  if (value === undefined || value.trim() === '') {
    throw new Error(`${name} is not set. See infra/.env.example.`);
  }
  return value.trim();
}

export function loadConfig(env: NodeJS.ProcessEnv = process.env): AppConfig {
  const isProduction = env['NODE_ENV'] === 'production';
  return {
    port: Number(env['PORT'] ?? 3000),
    databasePath: env['DATABASE_PATH'] ?? './aow5.db',
    // Required in production only, so `pnpm --filter aow5-utils-api dev` needs no
    // setup at all to answer /api/health.
    siteOrigin: isProduction ? required('SITE_ORIGIN') : (env['SITE_ORIGIN'] ?? 'http://localhost:5173'),
    freesoundToken: env['FREESOUND_TOKEN']?.trim() || null,
    steamApiKey: env['STEAM_API_KEY']?.trim() || null,
    discord: discordApp(env),
    assetsDir: env['ASSETS_DIR']?.trim() || defaultAssetsDir(isProduction),
    brandDir: env['BRAND_DIR']?.trim() || (isProduction ? './assets-brand' : '../../apps/webapp/src/assets'),
    /*
     * Derived from the database's own directory by default, so the one volume
     * that is already bind-mounted and backed up holds both. An explicit
     * `CARD_CACHE_DIR` overrides it for a deployment that wants the cache on
     * faster or more disposable storage.
     */
    cardCacheDir: env['CARD_CACHE_DIR']?.trim() || defaultCardCacheDir(env['DATABASE_PATH']),
    isProduction,
  };
}

/**
 * Both keys or nothing.
 *
 * A half-configured provider is the failure mode worth designing out: with only
 * an id, every attempt reaches Discord and comes back rejected, and the person
 * signing in has no way to tell that from their own mistake.
 */
function discordApp(env: NodeJS.ProcessEnv): AppConfig['discord'] {
  const clientId = env['DISCORD_CLIENT_ID']?.trim() ?? '';
  const clientSecret = env['DISCORD_CLIENT_SECRET']?.trim() ?? '';
  if (clientId === '' || clientSecret === '') return null;
  return { clientId, clientSecret };
}

/**
 * `./assets` in the image, the workspace copy in a checkout.
 *
 * Relative to the working directory in both cases — `/app` in the container,
 * `apps/api` for `pnpm dev` — so neither has to be told where it is running.
 */
function defaultAssetsDir(isProduction: boolean): string {
  return isProduction ? './assets' : '../../packages/aow5-shared/public';
}

/** `og/` next to the database file, or beside the working directory in development. */
function defaultCardCacheDir(databasePath: string | undefined): string {
  const path = databasePath?.trim() ?? '';
  // `:memory:` is a legal database path and has no directory. So does a bare
  // filename, whose `dirname` is `.` — which is the right answer for both.
  if (path === '' || path === ':memory:') return './og-cache';
  const slash = path.lastIndexOf('/');
  return slash <= 0 ? './og-cache' : `${path.slice(0, slash)}/og`;
}

export const CONFIG = Symbol('AppConfig');
